name: 书旗小说8
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 8,10 * * *'
jobs:
  build:
    runs-on: macos-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/chennfen/sqxs.git ~/sqxs
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x          
      - name: npm install
        run: |
          cd ~/sqxs/Task        
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
          
      - name: '【书旗小说8-视频】'
        run: |  
          cd ~/sqxs/Task
          node sqxs8_video.js      
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          
      - name: '【书旗小说8-阅读】'
        run: |  
          cd ~/sqxs/Task
          node sqxs8_read.js    
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
