name: 测试脚本
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      
      - name: '【测试】'
        run: |  
          cd ~/sqxs/Task/public
          node sqxs.js      
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}







