name: 测试
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/chennfen/sqxs.git ~/sqxs
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x          
      - name: npm install
        run: |
          cd ~/sqxs/Task/public        
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
          
          
      - name: '【书旗小说-视频】'
        run: |  
          cd ~/sqxs/Task/public
          node sqxs_video.js      
          
      - name: '【书旗小说-阅读】'
        run: |  
          cd ~/sqxs/Task/public
          node sqxs_read.js    



